/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fenetres;

/**
 *
 * @author cyril
 */
public class form_carte_de_credit extends javax.swing.JFrame {

    /**
     * Creates new form form_carte_de_credit
     */
    public form_carte_de_credit() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_annuler = new javax.swing.JButton();
        btn_valider = new javax.swing.JButton();
        fld_numero = new javax.swing.JTextField();
        fld_prenom = new javax.swing.JTextField();
        fld_nom = new javax.swing.JTextField();
        lbl_nom = new javax.swing.JLabel();
        lbl_numero = new javax.swing.JLabel();
        lbl_prenom = new javax.swing.JLabel();
        lbl_modif_num = new javax.swing.JLabel();
        lbl_numero1 = new javax.swing.JLabel();
        fld_numero1 = new javax.swing.JTextField();
        fld_numero2 = new javax.swing.JTextField();
        lbl_numero2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_annuler.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btn_annuler.setText("Annuler");
        btn_annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_annulerActionPerformed(evt);
            }
        });

        btn_valider.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btn_valider.setText("Valider");
        btn_valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_validerActionPerformed(evt);
            }
        });

        fld_numero.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        fld_numero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fld_numeroActionPerformed(evt);
            }
        });

        fld_prenom.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        fld_prenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fld_prenomActionPerformed(evt);
            }
        });

        fld_nom.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        fld_nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fld_nomActionPerformed(evt);
            }
        });

        lbl_nom.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_nom.setText("Nom :");

        lbl_numero.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_numero.setText("Numero :");

        lbl_prenom.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_prenom.setText("Prenom :");

        lbl_modif_num.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lbl_modif_num.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_modif_num.setText("Ajouter une carte");
        lbl_modif_num.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lbl_numero1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_numero1.setText("Cle :");

        fld_numero1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        fld_numero1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fld_numero1ActionPerformed(evt);
            }
        });

        fld_numero2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        fld_numero2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fld_numero2ActionPerformed(evt);
            }
        });

        lbl_numero2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_numero2.setText("Date d'expiration :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_modif_num, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_numero)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fld_numero))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_numero2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fld_numero2, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_nom)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fld_nom))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_prenom)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fld_prenom)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_numero1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fld_numero1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btn_valider, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_annuler, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_modif_num, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fld_numero1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_numero1))
                        .addGap(12, 12, 12)
                        .addComponent(btn_valider)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_annuler))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fld_numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_numero))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fld_numero2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_numero2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fld_nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_nom))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fld_prenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_prenom))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_annulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_annulerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_annulerActionPerformed

    private void btn_validerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_validerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_validerActionPerformed

    private void fld_numeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fld_numeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fld_numeroActionPerformed

    private void fld_prenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fld_prenomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fld_prenomActionPerformed

    private void fld_nomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fld_nomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fld_nomActionPerformed

    private void fld_numero1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fld_numero1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fld_numero1ActionPerformed

    private void fld_numero2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fld_numero2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fld_numero2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_carte_de_credit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_carte_de_credit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_carte_de_credit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_carte_de_credit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_carte_de_credit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_annuler;
    private javax.swing.JButton btn_valider;
    private javax.swing.JTextField fld_nom;
    private javax.swing.JTextField fld_numero;
    private javax.swing.JTextField fld_numero1;
    private javax.swing.JTextField fld_numero2;
    private javax.swing.JTextField fld_prenom;
    private javax.swing.JLabel lbl_modif_num;
    private javax.swing.JLabel lbl_nom;
    private javax.swing.JLabel lbl_numero;
    private javax.swing.JLabel lbl_numero1;
    private javax.swing.JLabel lbl_numero2;
    private javax.swing.JLabel lbl_prenom;
    // End of variables declaration//GEN-END:variables
}
