/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fenetres;

/**
 *
 * @author cyril
 */
public class form_adresse extends javax.swing.JFrame {

    /**
     * Creates new form form_adresse
     */
    public form_adresse() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_connexion = new javax.swing.JLabel();
        fld_pays = new javax.swing.JTextField();
        btn_annuler = new javax.swing.JButton();
        btn_valider = new javax.swing.JButton();
        fld_cp = new javax.swing.JTextField();
        fld_ville = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        area_adresse = new javax.swing.JTextArea();
        lbl_pays = new javax.swing.JLabel();
        lbl_cp = new javax.swing.JLabel();
        lbl_ville = new javax.swing.JLabel();
        lbl_adresse = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_connexion.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lbl_connexion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_connexion.setText("Ajouter une adresse");
        lbl_connexion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        fld_pays.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        fld_pays.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fld_paysActionPerformed(evt);
            }
        });

        btn_annuler.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btn_annuler.setText("Annuler");
        btn_annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_annulerActionPerformed(evt);
            }
        });

        btn_valider.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btn_valider.setText("Valider");
        btn_valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_validerActionPerformed(evt);
            }
        });

        fld_cp.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        fld_cp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fld_cpActionPerformed(evt);
            }
        });

        fld_ville.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        fld_ville.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fld_villeActionPerformed(evt);
            }
        });

        area_adresse.setColumns(20);
        area_adresse.setRows(5);
        jScrollPane1.setViewportView(area_adresse);

        lbl_pays.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_pays.setText("Pays :");

        lbl_cp.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_cp.setText("CP :");

        lbl_ville.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_ville.setText("Ville :");

        lbl_adresse.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_adresse.setText("Adresse :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_connexion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 22, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbl_pays)
                                    .addComponent(lbl_cp)
                                    .addComponent(lbl_ville)
                                    .addComponent(lbl_adresse))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(fld_ville, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                                    .addComponent(fld_cp)
                                    .addComponent(fld_pays)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btn_valider)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_annuler)))
                        .addGap(29, 29, 29))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_connexion, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fld_pays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_pays))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fld_ville, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_ville))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fld_cp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_cp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_adresse)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_valider)
                    .addComponent(btn_annuler))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fld_paysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fld_paysActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fld_paysActionPerformed

    private void btn_annulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_annulerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_annulerActionPerformed

    private void btn_validerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_validerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_validerActionPerformed

    private void fld_cpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fld_cpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fld_cpActionPerformed

    private void fld_villeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fld_villeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fld_villeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_adresse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_adresse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_adresse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_adresse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_adresse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area_adresse;
    private javax.swing.JButton btn_annuler;
    private javax.swing.JButton btn_valider;
    private javax.swing.JTextField fld_cp;
    private javax.swing.JTextField fld_pays;
    private javax.swing.JTextField fld_ville;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_adresse;
    private javax.swing.JLabel lbl_connexion;
    private javax.swing.JLabel lbl_cp;
    private javax.swing.JLabel lbl_pays;
    private javax.swing.JLabel lbl_ville;
    // End of variables declaration//GEN-END:variables
}
