/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fenetres;

import ihmclient.IhmClient;

/**
 *
 * @author cyril
 */
public class profil extends javax.swing.JFrame {

    /**
     * Creates new form accueil_1
     */
    public profil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_eatvite = new javax.swing.JLabel();
        lbl_connexion = new javax.swing.JLabel();
        lbl_inscription = new javax.swing.JLabel();
        lbl_pseudo = new javax.swing.JLabel();
        lbl_deco = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbl_bienvenue = new javax.swing.JLabel();
        lbl_panier = new javax.swing.JLabel();
        lbl_bienvenue1 = new javax.swing.JLabel();
        lbl_addresse1 = new javax.swing.JLabel();
        lbl_addresse2 = new javax.swing.JLabel();
        lbl_addresse3 = new javax.swing.JLabel();
        btn_adresse = new javax.swing.JButton();
        lbl_bienvenue2 = new javax.swing.JLabel();
        lbl_carte1 = new javax.swing.JLabel();
        lbl_carte2 = new javax.swing.JLabel();
        lbl_carte3 = new javax.swing.JLabel();
        btn_carte1 = new javax.swing.JButton();
        lbl_bienvenue3 = new javax.swing.JLabel();
        lbl_numero = new javax.swing.JLabel();
        btn_numero = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Profil");
        setMinimumSize(new java.awt.Dimension(1280, 720));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl_eatvite.setText("EAT' VITE");
        lbl_eatvite.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_eatviteMouseClicked(evt);
            }
        });

        lbl_connexion.setText("se connecter");
        lbl_connexion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_connexionMouseClicked(evt);
            }
        });

        lbl_inscription.setText("s'inscrire");
        lbl_inscription.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_inscriptionMouseClicked(evt);
            }
        });

        lbl_deco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_decoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_eatvite)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1057, Short.MAX_VALUE)
                .addComponent(lbl_deco)
                .addGap(18, 18, 18)
                .addComponent(lbl_inscription)
                .addGap(18, 18, 18)
                .addComponent(lbl_pseudo)
                .addGap(18, 18, 18)
                .addComponent(lbl_connexion)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_eatvite)
                    .addComponent(lbl_connexion)
                    .addComponent(lbl_inscription)
                    .addComponent(lbl_pseudo)
                    .addComponent(lbl_deco))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl_bienvenue.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbl_bienvenue.setText("Bienvenue !");

        lbl_panier.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_panier.setText("Mon panier");
        lbl_panier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_panierMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_panierMouseEntered(evt);
            }
        });

        lbl_bienvenue1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbl_bienvenue1.setText("Vos adresses :");

        lbl_addresse1.setText("42 Rue nullepart - Nowhere 42000");

        btn_adresse.setText("Ajouter");

        lbl_bienvenue2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbl_bienvenue2.setText("Vos cartes bleues");

        lbl_carte1.setText("Jean Personne : 1111-1111-1111-1111-1111");

        btn_carte1.setText("Ajouter");

        lbl_bienvenue3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbl_bienvenue3.setText("Votre numéro :");

        lbl_numero.setText("0102030405");

        btn_numero.setText("Modifier");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbl_bienvenue)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_panier))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_bienvenue1)
                                    .addComponent(lbl_addresse1)
                                    .addComponent(lbl_addresse2)
                                    .addComponent(lbl_addresse3)
                                    .addComponent(btn_adresse))
                                .addGap(405, 405, 405)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_carte1)
                                    .addComponent(lbl_carte3)
                                    .addComponent(lbl_carte2)
                                    .addComponent(lbl_carte1)
                                    .addComponent(lbl_bienvenue2)))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(lbl_numero)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_numero))
                                .addComponent(lbl_bienvenue3, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_panier)
                    .addComponent(lbl_bienvenue))
                .addGap(79, 79, 79)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_bienvenue1)
                    .addComponent(lbl_bienvenue2))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_addresse1)
                    .addComponent(lbl_carte1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_addresse2)
                    .addComponent(lbl_carte2))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_addresse3)
                    .addComponent(lbl_carte3))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_adresse)
                    .addComponent(btn_carte1))
                .addGap(110, 110, 110)
                .addComponent(lbl_bienvenue3)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_numero)
                    .addComponent(btn_numero))
                .addContainerGap(318, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_decoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_decoMouseClicked
        lbl_inscription.setText("s'inscrire");
        lbl_connexion.setText("se connecter");
        lbl_deco.setText("");
        lbl_pseudo.setText("");
    }//GEN-LAST:event_lbl_decoMouseClicked

    private void lbl_connexionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_connexionMouseClicked
        IhmClient.ouvrir_connexion();
        IhmClient.bloquer_profil();
    }//GEN-LAST:event_lbl_connexionMouseClicked

    private void lbl_inscriptionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_inscriptionMouseClicked
        IhmClient.bloquer_profil();
        IhmClient.ouvrir_inscription();
    }//GEN-LAST:event_lbl_inscriptionMouseClicked

    private void lbl_eatviteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_eatviteMouseClicked
        IhmClient.fermer_profil();
        IhmClient.ouvrir_accueil();
    }//GEN-LAST:event_lbl_eatviteMouseClicked

    private void lbl_panierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_panierMouseClicked
        IhmClient.fermer_profil();
        IhmClient.ouvrir_panier();
    }//GEN-LAST:event_lbl_panierMouseClicked

    private void lbl_panierMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_panierMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_panierMouseEntered

    public void changePseudo(String mail) {
        lbl_inscription.setText("");
        lbl_connexion.setText("");
        lbl_deco.setText("se déconnecter");
        lbl_pseudo.setText(mail);
        lbl_bienvenue.setText("Bienvenue " + lbl_pseudo.getText());
    }
    
    public void ajouterAdresse() {
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new accueil().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_adresse;
    private javax.swing.JButton btn_carte1;
    private javax.swing.JButton btn_numero;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_addresse1;
    private javax.swing.JLabel lbl_addresse2;
    private javax.swing.JLabel lbl_addresse3;
    private javax.swing.JLabel lbl_bienvenue;
    private javax.swing.JLabel lbl_bienvenue1;
    private javax.swing.JLabel lbl_bienvenue2;
    private javax.swing.JLabel lbl_bienvenue3;
    private javax.swing.JLabel lbl_carte1;
    private javax.swing.JLabel lbl_carte2;
    private javax.swing.JLabel lbl_carte3;
    private javax.swing.JLabel lbl_connexion;
    private javax.swing.JLabel lbl_deco;
    private javax.swing.JLabel lbl_eatvite;
    private javax.swing.JLabel lbl_inscription;
    private javax.swing.JLabel lbl_numero;
    private javax.swing.JLabel lbl_panier;
    private javax.swing.JLabel lbl_pseudo;
    // End of variables declaration//GEN-END:variables
}
